### ISSUE TITLE
for "quick profit"

### ISSUE THREAD

**Issue by formatme** [meepdarknessmeep/gproxy#2]
sir i think you under underestimate CitizenHack's sales and profits lmao
"The GProxy team are now taking back it's rightful throne as the best and most open lua state proxy" nice ego boost

**Comment by meepdarknessmeep** [comment]
good luck.

**Comment by KittoniuM** [comment]
formatme u better shut it nerd before i tell sl0w ur back to skidding again he will never help u paste dx9 aimbot again :D:D
